config/routes.rb
USport::Application.routes.draw do

  devise_for :users

  root to: "landing#index"

  resources :channels

  resources :user_channel_associations, only: :destroy

  resources :teams

  resources :players

  match :search, to: 'search#index', as: :search_index

  resources :users, only: [:index, :show, :edit, :update] do
    resources :favorite_channels, only: [:index, :create, :destroy]
  end

  resources :matches, except: :index do
    post :viewers, on: :member
    resources :moves, except: :show do
      match 'like' => 'moves#vote'
      resources :comments, only: [:index, :new, :create, :destroy]
    end
  end

  resources :authentications, :only => :create

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  # Autenticação com Facebook
  match '/auth/:provider/callback' => 'authentications#create'

  # Rota para autenticação de presença do Pusher
  get '/pusher/auth' => 'matches#auth'
  post '/pusher/auth' => 'matches#auth'

  # Rota para página about, que explica o funcionamento do uSport
  get '/about' => 'landing#about'

  # Rotas para central de ajuda
  match 'help', to: 'help#index'
  match 'help/:topic(.:format)', to: 'help#topic'
end

app/controllers/search_controller.rb
# encoding: utf-8
class SearchController < ApplicationController
  skip_authorization_check

  def index
    @users = User.search_by_attrs(params[:q])
    @teams = Team.search_by_attrs(params[:q])
    @players = Player.search_by_attrs(params[:q])
    @matches = Match.includes(:channel, :teams).search_by_attrs(params[:q])
    flash[:notice] = "#{@users.length} usuário(s), #{@teams.length} time(s), " + \
      "#{@players.length} jogador(es) e #{@matches.length} partidas encontrada(s)"
  end
end

app/views/search/index.html.erb
<div class='well'>
<% @matches.find_each do |match| %>
  <div class="media">
    <a class="pull-left">
      <%= image_tag 'icons/touchdown.png', width: '90px' %>
    </a>
    <div class="media-body">
      <%= link_to match_path(match) do %>
        <h4 class="media-heading"><%= match.name %> <small>(partida)</small></h4>
      <% end %>
      <%= match.place %>
      <%= l match.date, format: :short %>
      por <%= match.channel.name %>
    </div>
  </div>
<% end %>
<%= @users.find_each do |user| %>
  <div class="media">
    <a class="pull-left">
      <%= image_tag user.avatar(:thumb_90) %>
    </a>
    <div class="media-body">
      <h4 class="media-heading"><%= user.display_name %> <small>(usuário)</small></h4>
      <%= user.username %>
    </div>
  </div>
<% end %>
<%= @players.find_each do |player| %>
  <div class="media">
    <a class="pull-left">
      <%= image_tag 'avatars/missing.gif' %>
    </a>
    <div class="media-body">
      <h4 class="media-heading"><%= player.display_name %> <small>(jogador)</small></h4>
    </div>
    #<%= player.number %>
    <%= player.position %>
    <%= player.team.name %>
  </div>
<% end %>
<%= @teams.find_each do |team| %>
  <div class="media">
    <a class="pull-left">
      <%= image_tag team.avatar(:thumb_90) %>
    </a>
    <div class="media-body">
      <%= link_to team_path(team) do %>
        <h4 class="media-heading"><%= team.name %> <small>(time)</small></h4>
      <% end %>
      <%= team.abbreviation %>
      <%= team.sport_type %>
    </div>
  </div>
<% end %>
</div>