config/routes.rb
USport::Application.routes.draw do

  devise_for :users

  root to: "landing#index"

  resources :channels

  resources :user_channel_associations, only: :destroy

  resources :teams

  resources :players

  match :search, to: 'search#index', as: :search_index

  resources :users, only: [:index, :show, :edit, :update] do
    resources :favorite_channels, only: [:index, :create, :destroy]
  end

  resources :matches, except: :index do
    post :viewers, on: :member
    resources :moves, except: :show do
      match 'like' => 'moves#vote'
      resources :comments, only: [:index, :new, :create, :destroy]
    end
  end

  resources :authentications, :only => :create

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  # Autenticação com Facebook
  match '/auth/:provider/callback' => 'authentications#create'

  # Rota para autenticação de presença do Pusher
  get '/pusher/auth' => 'matches#auth'
  post '/pusher/auth' => 'matches#auth'

  # Rota para página about, que explica o funcionamento do uSport
  get '/about' => 'landing#about'

  # Rotas para central de ajuda
  match 'help', to: 'help#index'
  match 'help/:topic(.:format)', to: 'help#topic'
end

app/views/shared/_footer.html.erb
<footer class="row-fluid">
   <p class="text-center">Copyright © 2013 Quince Minds</p>
</footer>

app/views/shared/_leftbar.html.erb
<ul class='well nav nav-list'>
  <li class = <%= "active" if @active_page == "Home" %> ><%= link_to '<i class="icon-tint"></i> Eventos'.html_safe, "/"  %></li>
  <li class = <%= "active" if @active_page == "Channels" %> ><%= link_to '<i class="icon-desktop"></i> Canais'.html_safe, "/channels"  %></li>
  <% if current_user %>
    <li class = <%= "active" if @active_page == "UserChannels" %> ><%= link_to '<i class="icon-user-md"></i> Meus Canais'.html_safe, channels_path(user_id: current_user) %></li>
    <li class = <%= "active" if @active_page == "FavoriteChannels" %> >
      <%= link_to '<i class="icon-heart-empty"></i> Canais Favoritos'.html_safe,
        user_favorite_channels_path(current_user) %>
    </li>
  <% end %>
  <li class = <%= "active" if @active_page == "Esportes" %> ><%= link_to '<i class="icon-group"></i> Esportes'.html_safe, root_path(sport: 'soon') %></li>
</ul><hr />
<div class='well'>
  <h5>Bem-Vindo!</h5>Quer saber mais sobre o <b>uSport</b>? Veja nossa
  <%= link_to 'página para iniciantes', '/about' %> ou visite o nosso
  <b><%= link_to 'blog', 'http://blog.quince.com.br' %></b>.
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to root_path, :class => 'brand' do %>
        <%= image_tag 'logoUSport.png', style: 'width: 50px' %>
      <% end %>
      <div class="nav-collapse collapse">
        <ul class='nav'>
          <li>
            <%= link_to 'Transmitir!', new_match_path %>
          </li>
          <% if can? :create, Team %>
            <li class="divider-vertical"></li>
            <li>
              <%= link_to 'Gerenciar times e jogadores', teams_path %>
            </li>
          <% end %>
          <li class="divider-vertical"></li>
          <li>
            <%= form_for '', url: search_index_path, html: { class: 'navbar-search form-search' } do |f| %>
              <div class="input-append">
                <%= f.text_field :q, class: 'search-query search', style: 'border-right: 0' %>
                <%= button_tag(value: 'submit', class: 'btn', style: 'border-left: 0') do %>
                  <i class='icon-search'></i>
                <% end %>
              </div>
            <% end %>
          </li>
        </ul>
        <ul class="nav pull-right">
          <% if current_user %>
            <li class="dropdown">
              <%= link_to '#', :class => 'dropdown-toggle', :'data-toggle' => 'dropdown' do %>
              <%= current_user.first_name %>
              <i class="icon-large icon-user"></i>
              <b class="caret"></b>
              <% end %>
              <ul class="dropdown-menu">
                <li><%= link_to '<i class="icon-large icon-user"></i> Perfil'.html_safe, user_path(current_user) %></li>
                <li><%= link_to '<i class="icon-wrench"></i> Conta'.html_safe, edit_user_path(current_user) %></li>
                <li><%= link_to '<i class="icon-signout"></i> Sair'.html_safe, logout_path %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Ainda não tem conta? Cadastre-se!', new_user_registration_path %></li>
            <li class="dropdown">
              <a class="dropdown-toggle" href="#" data-toggle="dropdown">Entrar <strong class="caret"></strong></a>
              <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
                <%= render :partial => 'sessions/new',
                  :locals => { :resource => User.new, :resource_name => 'user' } %>
              </div>
            </li>
          <% end %>
        </ul>

        <ul class="nav hidden-desktop">
          <li><%= link_to '<i class="icon-tint"></i> Eventos'.html_safe, "/"  %></li>
          <li><%= link_to '<i class="icon-desktop"></i> Canais'.html_safe, "/channels"  %></li>
          <% if current_user %>
            <li><%= link_to '<i class="icon-user-md"></i> Meus Canais'.html_safe, channels_path(user_id: current_user) %></li>
            <li>
              <%= link_to '<i class="icon-heart-empty"></i> Canais Favoritos'.html_safe,
                user_favorite_channels_path(current_user) %>
            </li>
          <% end %>
          <li><%= link_to '<i class="icon-group"></i> Esportes'.html_safe %></li>
        </ul>

      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>