config/routes.rb
USport::Application.routes.draw do

  devise_for :users

  root to: "landing#index"

  resources :channels

  resources :user_channel_associations, only: :destroy

  resources :teams

  resources :players

  match :search, to: 'search#index', as: :search_index

  resources :users, only: [:index, :show, :edit, :update] do
    resources :favorite_channels, only: [:index, :create, :destroy]
  end

  resources :matches, except: :index do
    post :viewers, on: :member
    resources :moves, except: :show do
      match 'like' => 'moves#vote'
      resources :comments, only: [:index, :new, :create, :destroy]
    end
  end

  resources :authentications, :only => :create

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  # Autenticação com Facebook
  match '/auth/:provider/callback' => 'authentications#create'

  # Rota para autenticação de presença do Pusher
  get '/pusher/auth' => 'matches#auth'
  post '/pusher/auth' => 'matches#auth'

  # Rota para página about, que explica o funcionamento do uSport
  get '/about' => 'landing#about'

  # Rotas para central de ajuda
  match 'help', to: 'help#index'
  match 'help/:topic(.:format)', to: 'help#topic'
end

app/models/move.rb
# encoding: utf-8
class Move < ActiveRecord::Base
  attr_accessible :description, :kind, :minute, :player, :points, :quarter, :yards,
    :team, :match, :player_id, :team_id

  acts_as_votable

  # Associações
  belongs_to :match
  belongs_to :player
  belongs_to :team #TODO Restrição: deve ser o mesmo time do jogador
  has_many :comments

  # Validações
  validates_presence_of :kind, :match #, :player

  def self.points_for(move_kind)
    case move_kind
    when 'touchdown-run', 'touchdown-pass', 'touchdown-return'
      6
    when 'fieldgoal'
      3
    when 'safety'
      2
    when 'two-point-conversion'
      2
    when 'extrapoint'
      1
    else
      0
    end
  end

  def main
    case self.kind
    when 'comment'
      "Comentário do transmissor"
    when 'end'
      "Fim de partida"
    when 'time'
      "Timeout!"
    else
      if(self.player) then
        "#{self.kind.capitalize}, #{self.player.try(:display_name)} (##{self.player.try(:number)})!"
      else
        "#{self.kind.capitalize}!"
      end  
    end
  end

  def message
    case self.kind
    when "punt"
      "Retorno de #{self.yards} jardas." if self.yards
    when "extrapoint"

    when "penalty"

    when "kickoff"
      "Chute de #{self.yards} jardas." if self.yards
    when "fumble"
      "O jogador deixou a bola cair."
    when "run"
      "O jogador teve um ganho de #{self.yards} jardas." if self.yards
    when "turnover"

    when "time"
      "Pedido de tempo dos #{self.team.name}" if self.team
    when "touchdown-run"
      if self.yards
        "O jogador correu #{self.yards} jardas até a endzone! 6 pontos para o(s) #{self.team.name}!"
      end
    when "touchdown-pass"

    when "touchdown-return"

    when "fieldgoal"
      "3 pontos para o(s) #{self.team.name}!" if self.team
    when "pass"
      "Passe de QB para WR para um ganho de #{self.yards} jardas." if self.yards
    when "sack"
      if self.yards
        "O quarterback foi derrubado para uma perda de #{self.yards} jardas."
      end
    when "interception"
      "Após passe do quarterback, a bola foi interceptada!"
    when "safety"
      "O quarterback foi derrubado dentro da endzone!"
    when "two-point-conversion"
      "Após um touchdown, o(s) #{self.team.name} fizeram uma conversão de dois pontos!"
    when "comment"

    when "end"

    end
  end
end

app/controllers/moves_controller.rb
# encoding: utf-8
class MovesController < ApplicationController

  # carrega jogadas de uma partida por javascript
  def index
    @moves = Match.find(params[:match_id]).moves.includes(:team, :match, :player).
      order('created_at DESC').page(params[:page])
    authorize! :show, Move
    respond_to do |format|
      format.js
    end
  end

  def new
    @match = Match.find(params[:match_id])
    authorize! :manage, @match
    @move = Move.new
    @kinds = [["Punt", "punt"], ["Extrapoint", "extrapoint"], ["Penalty", "penalty"],
      ["Kickoff", "kickoff"], ["Fumble", "fumble"], ["Tackle", "tackle"],
      ["Run", "run"], ["Turnover", "turnover"], ["Time", "time"],
      ["Touchdown (Corrida)", "touchdown-run"], ["Touchdown (Retorno)", "touchdown"],
      ["Touchdown (Passe)", "touchdown-pass"], ["Fieldgoal", "fieldgoal"],
      ["Pass", "pass"], ["Sack", "sack"], ["Interception", "interception"],
      ["Safety", "safety"], ["Two-point conversion", "two-point-conversion"],
      ["Comentário", "comment"], ["Fim de Jogo", "end"]]
    @minutes = [["--", 0]]
    15.times do |n|
      @minutes << [(n+1).to_s, (n+1)]
    end
    @yards = []
    (-50..50).to_a.each do |n|
      @yards << [n.to_s, n]
    end
  end

  def create
    team = Team.find(params[:move].delete(:team))
    @match = Match.find(params[:match_id])
    unless !params[:move][:player] || params[:move][:player]
      player = team.find_player_by_text_input(params[:move][:player])
      authorize! :manage, Move.new(match: @match)
      unless player
        render js: "$('#player input').val(''); $('#player input').attr('placeholder', 'Informe um jogador válido'); $('#player input').focus();" and return
      end
    end
    params[:move].delete(:player)
    points = Move.points_for(params[:move][:kind])
    @move = Move.create(params[:move]) do |move|
      move.player = player
      move.team = team
      move.match = @match
      move.points = points
      authorize! :create, move
    end
    # Atualiza o placar da partida
    if team == @match.teams[0]
      @match.value1 = @match.value1 + points
    else
      @match.value2 = @match.value2 + points
    end
    @match.save

    respond_to do |format|
      format.html { render 'create.js.erb' }
      format.js
    end
  end

  def edit
    @move = Move.find(params[:id])
    @match = @move.match
    authorize! :manage, @move
    @kinds = [["Punt", "punt"], ["Extrapoint", "extrapoint"], ["Penalty", "penalty"],
      ["Kickoff", "kickoff"], ["Fumble", "fumble"], ["Tackle", "tackle"],
      ["Run", "run"], ["Turnover", "turnover"], ["Time", "time"],
      ["Touchdown (Corrida)", "touchdown-run"], ["Touchdown (Retorno)", "touchdown"],
      ["Touchdown (Passe)", "touchdown-pass"], ["Fieldgoal", "fieldgoal"],
      ["Pass", "pass"], ["Sack", "sack"], ["Interception", "interception"],
      ["Safety", "safety"], ["Two-point conversion", "two-point-conversion"],
      ["Comentário", "comment"], ["Fim de Jogo", "end"]]
    @minutes = [["--", 0]]
    15.times do |n|
      @minutes << [(n+1).to_s, (n+1)]
    end
    @yards = []
    151.times do |n|
      @yards << [n.to_s, n]
    end
  end

  def update
    @move = Move.find(params[:id])
    authorize! :manage, @move
    team = Team.find(params[:move].delete(:team)) if params[:move][:team]
    if params[:move][:player]
      player = Player.find_by_text_input(params[:move].delete(:player))
    end
    @move.update_attributes(params[:move])
    @move.player = player if player
    @move.team = team if team
    if @move.save
      flash[:notice] = 'Jogada atualizada!'
      redirect_to match_path(@move.match)
    else
      flash.now[:alert] = 'Não foi possível atualizar a jogada. Verifique os dados.'
      render 'edit'
    end
  end

  def destroy
    @move = Move.find(params[:id])
    team = @move.team
    @match = @move.match
    points = Move.points_for(@move.kind)
    authorize! :manage, @move
    # Atualiza o placar da partida
    if team == @match.teams[0]
      @match.value1 = @match.value1 - points
    else
      @match.value2 = @match.value2 - points
    end
    @match.save
    @move.destroy
    respond_to do |format|
      format.html do
        flash[:notice] = 'A jogada foi removida.'
        redirect_to match_path(@move.match)
      end
      format.js
    end
  end

  def vote
    @move = Move.find(params[:move_id])
    authorize! :show, @move
    @move.liked_by current_user

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/moves_helper.rb
module MovesHelper
  # Recebe um move e retorna o outro time da partida (que não é o do move)
  def the_other_team_from(move)
    move.team == move.match.teams[0] ? move.match.teams[1] : move.match.teams[0]
  end
end

app/views/moves/_desktop_form.html.erb
<%= form_for Move.new, url: { match_id: @match, action: 'create', controller: 'moves' },
  :html => { autocomplete: 'off' }, remote: 'true' do |f| %>
  <%= f.hidden_field :kind, id: 'kind', value: ''%>
  <%= f.label :team %>
  <%= f.select :team,
    options_for_select(@match.teams.collect { |t| [t.name, t.id] }) %>
  <%= f.label :player %>
  <%= f.text_field :player, class: 'typeahead player',
    autocomplete: 'off', required: 'true'%>
  <%= f.label :yards %>
  <%= f.text_field :yards %>
  <%= f.label :description %>
  <%= f.text_area :description, cols: "30", rows: "8", style: "resize: none;" %>
  <div class="modal-fotter">
    <%= f.submit id:'submit', :class => "btn", :'aria-hidden' => 'true' %>
  </div>
<% end %>

app/views/moves/_mobile_form.html.erb
<%= form_for @move, url: path, remote: remote, autocomplete: :off do |f| %>
  <% unless ['end'].include?(@move.kind) %>
    <div>
      <%= f.label :quarter %>
      <%= f.select :quarter, options_for_select([["--", 0], ["First", 1],
      ["Second", 2], ["Third", 3], ["Fourth", 4]], @move.quarter) %>
    </div>
  <% end %>

  <div>
    <%= f.label :kind %>
    <% if action == 'update' %>
      <%= f.select :kind, options_for_select(@kinds, @move.kind), {},
        disabled: true %>
    <% else %>
      <%= f.select :kind, options_for_select(@kinds, @move.kind) %>
    <% end %>
  </div>

  <% unless ['end', 'comment'].include?(@move.kind) %>
    <div>
      <%= f.label :team %>
      <%= f.select :team,
        options_for_select(@match.teams.collect { |t| [t.name, t.id] },
          @move.team.try(:id)) %>
    </div>
  <% end %>

  <% unless ['comment', 'time', 'end'].include?(@move.kind) %>
    <div>
      <%= f.label :yards %>
      <%= f.number_field :yards %>
    </div>
  <% end %>

  <% unless ['end'].include?(@move.kind) %>
    <div>
      <%= f.label :minute %>
      <%= f.select :minute, options_for_select(@minutes, @move.minute) %>
    </div>
  <% end %>

  <% unless ['comment', 'time', 'end'].include?(@move.kind) %>
    <div>
      <%= f.label :player %>
      <% value = "##{@move.player.number} #{@move.player.first_name}" if @move.player %>
      <%= f.text_field :player, class: 'typeahead player', value: value,
        autocomplete: :off, required: :true %>
      <span class="help-block">Ex.: #35 Terrence Cody</span>
    </div>
  <% end %>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description, cols: "30", rows: "8", style: "resize: none;" %>
  </div>
  <%= f.submit nil, onclick: "$('html, body').animate({ scrollTop: 0 });" , :'data-target' => ".new-move-collapse", :'data-toggle' => "collapse", class: "btn" %>
<% end %>

app/views/moves/_move.html.erb
<tr class='move' id="<%= move.id %>">
  <%# primeira parte da tabela, com imagem do time e quarto %>
  <td width="40px">
    <% unless move.kind == 'comment' || move.kind == 'penalty' %>
      <%= image_tag(move.team.avatar, id: "thumb", class: "img-polaroid img-rounded",
        style: 'height: 40px; width: 40px;') %>
    <% end %>
    <% if move.kind == 'penalty' %>
      <%= image_tag(the_other_team_from(move).avatar, id: "thumb", class: "img-polaroid img-rounded",
        style: 'height: 40px; width: 40px;') %>
    <% end %>
    <% if move.quarter && move.quarter !=0 %>
      <h3 align="center"> <%= move.quarter.to_s + "º" %></h3>
    <% end %>
  </td>

  <%#Segunda parte da tabela, onde ficam as mensagens da jogada. Links de edit,
  comentários etc%>
  <td>
    <p><b><%= move.main %></b> <%= move.message %></p>
    <p><%= move.description %></p>
    <ul class="inline">
      <li>
        <%= link_to match_move_like_path(move.match, move), remote: true do %>
          <i class="icon-thumbs-up" title='Curtir'></i>
        <% end %>
      </li>
      <li>
        <span id='move-<%= move.id %>-votes'><%= move.votes.length %></span>
      </li>
      <li>
        <%= link_to '#show-comments', class: 'show-comments' do %>
          <i class="icon-comment" title='Mostrar Comentários'></i>
        <% end %>
      </li>
      <li class='comment-count'>
        <%= move.comments.length %> Comentário(s)
      </li>
      <li class ="text-right muted" data-toggle="tooltip"
        title="<%= l move.created_at, format: :long %>" >
        <%= time_ago_in_words(move.created_at, include_seconds = true).
          gsub("aproximadamente", "±") %> atrás
      </li>
    </ul>
    <% if show_comment_button %>
      <%= content_tag 'a', class: 'btn comment', id: move.id do %>
        <i class="icon-comment"></i> Comentar
      <% end %><br class='hidden-desktop' /><br class='hidden-desktop' />
    <% end %>
    <% if (can? :manage, move) && show_edition_buttons %>
      <%= link_to edit_match_move_path(move.match, move),
        class: 'btn' do %>
        <i class="icon-cog"></i> Editar
      <% end %><br class='hidden-desktop' /><br class='hidden-desktop' />
      <%= link_to match_move_path(move.match, move),
        method: :delete, remote: :true, class: 'btn btn-danger' do %>
        <i class="icon-trash icon-white"></i> Remover
      <% end %>
    <% end %>
    <div id='form-for-comment' style='display: none'>
      <br />
      <%= form_for Comment.new, url: match_move_comments_path(move.match, move),
        remote: true do |f| %>
        <%= f.text_area :body, rows: 4 %><br />
        <%= f.submit nil, class: 'btn' %>
      <% end %>
    </div>
    <div class='comments' style='display: none'>
      <% move.comments.each do |comment| %>
        <%= render comment %>
      <% end %>
    </div>
  </td>
</tr>

app/views/moves/create.js.erb
<%# Exibe a jogada na tela do criador %>
$('#moves').prepend("<%= j render(@move, show_comment_button: :true, show_edition_buttons: true) %>");
$('#empty-message').hide();
<%# Atualiza o placar da partida %>
$('#team1-score').html(<%= @match.value1 %>);
$('#team2-score').html(<%= @match.value2 %>);
<%# Reseta o formulário de nova jogada %>
$('#new_move input[type=text], textarea').val("");
$('#move_yards').val(0);
<%# Esconde o modal %>
$('#NewMoveForm').modal('hide');

app/views/moves/destroy.js.erb
$("#<%= @move.id %>").remove();

app/views/moves/edit.html.erb
<%= render partial: 'mobile_form', locals: { action: 'update', remote: nil,
  path: match_move_path(@move.match, @move) } %>

app/views/moves/index.js.erb
$('#moves').append("<%= j render(@moves, show_comment_button: :true, show_edition_buttons: :true) %>");
$('#show-more').replaceWith("<%= j (link_to_next_page(@moves, 'Mostrar mais...',
  rel: 'next', remote: true, class: 'btn', id: 'show-more')) %>")
<% if @moves.last_page? %>
  $("#show-more").remove();
<% end %>

app/views/moves/new.html.erb
<%= render partial: 'form', locals: { action: 'create', remote: 'true' } %>

app/views/moves/show.js.erb
<% unless current_user && current_user == @move.channel.owner %>
  $('#moves').prepend("<%= j render(@move, show_comment_button: :true, show_edition_buttons: true) %>");
  $('#empty-message').hide();
<% end %>

app/views/moves/vote.js.erb
$('#move-<%= @move.id %>-votes').html('<%= @move.votes.length %>');