config/routes.rb
USport::Application.routes.draw do

  devise_for :users

  root to: "landing#index"

  resources :channels

  resources :user_channel_associations, only: :destroy

  resources :teams

  resources :players

  match :search, to: 'search#index', as: :search_index

  resources :users, only: [:index, :show, :edit, :update] do
    resources :favorite_channels, only: [:index, :create, :destroy]
  end

  resources :matches, except: :index do
    post :viewers, on: :member
    resources :moves, except: :show do
      match 'like' => 'moves#vote'
      resources :comments, only: [:index, :new, :create, :destroy]
    end
  end

  resources :authentications, :only => :create

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  # Autenticação com Facebook
  match '/auth/:provider/callback' => 'authentications#create'

  # Rota para autenticação de presença do Pusher
  get '/pusher/auth' => 'matches#auth'
  post '/pusher/auth' => 'matches#auth'

  # Rota para página about, que explica o funcionamento do uSport
  get '/about' => 'landing#about'

  # Rotas para central de ajuda
  match 'help', to: 'help#index'
  match 'help/:topic(.:format)', to: 'help#topic'
end

app/models/match.rb
class Match < ActiveRecord::Base
  include PgSearch

  # Atributos acessíveis
  attr_accessible :date, :name, :type, :value1, :value2, :channel, :channel_id,
    :place

  # Associações
  has_many :moves
  has_and_belongs_to_many :teams
  belongs_to :channel

  # Validações
  validates_presence_of :date, :name, :channel
  validates_length_of :name, in: 5..80

  # Busca
  pg_search_scope :search_by_attrs,
    against: [:name], associated_against: { teams: :name },
    using: { tsearch: { prefix: true } }

  def day
    I18n.l(date.to_date, format: :long)
  end
end

app/models/matches/football_match.rb
class FootballMatch < Match
end

app/controllers/matches_controller.rb
# encoding: utf-8
class MatchesController < ApplicationController
  protect_from_forgery :except => [:auth, :viewers] # stop rails CSRF protection for this action
  skip_authorization_check only: [:auth, :viewers]
  layout :choose_layout

  def show
    @match = Match.find(params[:id])
    authorize! :show, @match
    # @user = User.find(params[:user_id])
    @moves = @match.moves.includes(:team, :match, :player, :votes,
      comments: [:author, :move]).
      order('created_at DESC').page(params[:page])
    # Daqui para baixo são setadas as variáveis utilizadas para criação de move
    @move = Move.new(:match => @match)
    if can?(:create, @move)
      @kinds = [["Punt", "punt"], ["Extrapoint", "extrapoint"], ["Touchdown (Corrida)", "touchdown-run"],
        ["Touchdown (Retorno)", "touchdown"],
        ["Touchdown (Passe)", "touchdown-pass"],
        ["Kickoff", "kickoff"], ["Field Goal", "fieldgoal"],
        ["Fumble", "fumble"], ["Interceptação", "interceptation"], ["Falta", "penalty"],
        ["Sack", "sack"], ["Fim de jogo", "end"],
        ["Tempo", "time"], ["Turnover", "turnover"], ["Comentário", "comment"],
        ["Passe", "pass"], ["Corrida", "run"]]
      @minutes = [["--", 0]]
      15.times do |n|
        @minutes << [(n+1).to_s, (n+1)]
      end
      @yards = []
      151.times do |n|
        @yards << [n.to_s, n]
      end
    end
    session[:return_to] = request.fullpath if !current_user
  end

  def new
    authorize! :manage, Channel.find_by_id(params[:channel_id]) || current_user.try(:channels).try(:first)
    @match = FootballMatch.new #FIXME Por enquanto, apenas partidas desse tipo
    authorize! :create, Match
    @teams = Team.all # necessário para formulário de criação
  end

  def create
    channel = Channel.find(params[:football_match][:channel_id])
    authorize! :manage, channel
    teams = params[:football_match].delete(:teams_ids) if params[:football_match][:teams_ids]
    @teams = Team.all
    @match = FootballMatch.new(params[:football_match]) do |m|
      m.teams << Team.find(teams) if teams
      m.channel = channel
    end
    if params[:date] # atualiza a hora da partida sem modificar a data
      @match.date = @match.date.change(:hour => params[:date][:'time(4i)'].to_i ,
        :min => params[:date][:'time(5i)'].to_i)
    end
    if @match.save
      flash[:notice] = 'Partida criada!'
      redirect_to match_path(@match)
    else
      flash.now[:alert] = 'Ops! Não foi possível criar a partida.'
      render 'new'
    end
  end

  def edit
    @match = Match.find(params[:id])
    @teams = Team.all # necessário para formulário de edição
    authorize! :manage, @match
  end

  def update
    match = Match.find(params[:id])
    authorize! :manage, match
    teams = params[:football_match].delete(:teams_ids) if params[:football_match][:teams_ids]
    match.update_attributes(params[:football_match])
    match.teams = Team.find(teams) if teams
    if match.save
      flash[:notice] = 'Partida atualizada!'
    else
      flash[:error] = 'Ops! Não foi possível atualizar a partida.'
    end

    redirect_to match_path(match)
  end

  def destroy
    @match = Match.find(params[:id])
    authorize! :manage, @match
    if @match.destroy
      flash[:notice] = 'Partida removida!'
      redirect_to channel_path(@match.channel)
    else
      flash[:error] = 'Ops! Não foi possível remover a partida.'
      redirect_to match_path(@match)
    end
  end

  def score
    @match = Match.find(params[:id])
  end

  def auth
    response = Pusher[params[:channel_name]].authenticate(params[:socket_id], {
        user_id: SecureRandom.hex(4) #DISCUSS Solução para usuários não logados
      })
    render json: response.stringify_keys!
  end

  def viewers
    webhook = Pusher.webhook(request)
    if webhook.valid?
      webhook.events.each do |event|
        match = Match.find(event["channel"].rpartition('-').last)
        count = parse_count_from_json(Pusher.get("/channels/#{event['channel']}",
          info: 'user_count'))
        match.update_attribute(:viewers_count, count)
      end
    end
    render nothing: true
  end

  private

  def choose_layout
    if action_name == "score"
      "clean"
    else
      "application"
    end
  end

  def parse_count_from_json(response)
    if response[:occupied]
      response[:user_count]
    else
      0
    end
  end

end

app/helpers/matches_helper.rb
module MatchesHelper
  def many_yards
    yards = []
    (-50..50).to_a.each do |n|
      yards << [n.to_s, n]
    end

    yards
  end
end

app/views/matches/_form.html.erb
<%= form_for @match, url: { action: action } do |f| %>
  <%= f.hidden_field :channel_id, value: current_user.channels.first.id %>
  <%= f.label :name %>
  <%= '<div class="control-group error">'.html_safe if @match.errors.messages[:name].first %>
    <div class="controls">
      <%= f.text_field :name, :placeholder => "Nome da partida" %>
      <span class="help-inline"><%= @match.errors.messages[:name].first %></span>
    </div>
  <%= '</div>'.html_safe if @match.errors.messages[:name].first %>

  <%= f.label :date %>
  <%= f.date_select :date %>

  <%= f.label :hour %>
  <%= time_select :date, "time" %><br />

  <%= f.label :place %>
  <%= f.text_field :place %>
  <%= f.label :type %>
  <%= f.select :type, options_for_select([["Futebol Americano", "FootballMatch"]]) %><br />
  <%= '<div class="control-group error">'.html_safe if @match.errors.messages[:teams].try(:first) %>
    <%= f.label :team1 %>
    <%= select_tag('football_match[teams_ids][]', options_for_select(@teams.collect { |t| [t.name, t.id] })) %><br />
    <span class="help-inline">não pode ser o mesmo que time 2</span>
    <%= f.label :team2 %>
    <%= select_tag('football_match[teams_ids][]', options_for_select(@teams.collect { |t| [t.name, t.id] }, 2)) %><br />
    <span class="help-inline">não pode ser o mesmo que time 1</span>
  <%= '</div>'.html_safe if @match.errors.messages[:teams].try(:first) %>
  <br />
  <%= f.submit nil, class: 'btn' %>
<% end %>

app/views/matches/_new_move.html.erb
<%= form_for @move, :url => match_moves_path(@match), remote: :true do |f| %>
  <div style="float: left" >
     <%= f.label :description, :value => "Descrição" %>
    <%= f.text_area :description, :cols => "30", :rows => "8", :style => "resize: none;" %>
  </div>
  <div style="float: right">
     <div>
    <%= f.label :quarto %>
    <%= f.select :quarter, options_for_select([["--", 0], ["First", 1],
      ["Second", 2], ["Third", 3], ["Fourth", 4]]) %>
    </div>
     <div>
      <%= f.label :tempo %>
      <%= f.select :minute, options_for_select(@minutes) %>
    </div>
     <div>
      <%= f.label :jardas %>
      <%= f.select :yards, options_for_select(@yards) %>
    </div>
  </div>
  <div>
    <%= f.label :time %>
    <%= f.select :team,
    options_for_select(@match.teams.collect { |t| [t.name, t.id] }) %>
  </div>
  <div>
    <%= f.label :jogador %>
    <%= f.select :player,
      options_for_select(Player.all.collect { |p| [p.first_name, p.id] }) %>
  </div>
  <div>
    <%= f.label :jogada %>
    <%= f.select :kind, options_for_select(@kinds) %>
  </div>

  <div>
    <%= f.submit :class => "btn"%>
  </div>
<% end %>

app/views/matches/_preview.html.erb
<li class="span3">
  <div class="thumbnail">
    <table class="table table-striped" style="margin-bottom: 0px">
      <thead>
        <tr>
          <th colspan="3" style="line-height: 5px">
            <p>
              <%= link_to preview.name, match_path(preview) %> |
              <span id='match-<%= preview.id %>-viewers' class='team-avatar label'
                data-toogle='tooltip' data-placement='top'
                data-original-title='Fãs acompanhando esta partida'>
                <%= preview.viewers_count %>
              </span>
            </p>
            <p class="muted" style="font-size: 11px">
              por
              <%= link_to(preview.channel.owner.display_name, user_path(preview.channel.owner)) %>
              <span style="padding: 0px 5px">.</span>
              <%= time_ago_in_words(preview.created_at, include_seconds=true).gsub('aproximadamente','±')%>
            </p>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td width="33%" style="text-align: right">
            <%= image_tag(preview.teams[0].avatar(:thumb_90), style: "width: 50px",
              class: 'team-avatar', :'data-toggle' => 'tooltip',
              :'data-placement' => 'top', :'data-original-title' => preview.teams[0].name) %><br />
            <%= preview.teams[0].abbreviation %>
          </td>
          <td width="33%"  style="text-align: center; white-space: nowrap">
            <h3> <%= preview.value1.to_s + " X " + preview.value2.to_s%> </h3>
          </td>
          <td width="33%" style="text-align: left">
            <%= image_tag(preview.teams[1].avatar(:thumb_90),  style: "width: 50px",
              class: 'team-avatar', :'data-toggle' => 'tooltip',
              :'data-placement' => 'top', :'data-original-title' => preview.teams[1].name) %><br />
            <%= preview.teams[1].abbreviation %>
          </td>
        </tr>
        <tr>
          <td colspan="3">
            <% if preview.place? %>
              <p><%= preview.place %></p>
            <% else %>
              <p><%= "--"%><p>
            <% end %>
            <p><%= l preview.date, format: :short %></p>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</li>

app/views/matches/edit.html.erb
<% content_for(:include_js) { 'matches' } %>

<%= render partial: 'form', locals: { action: 'update' } %>

app/views/matches/new.html.erb
<% content_for(:include_js) { 'matches' } %>

<%= render partial: 'form', locals: { action: 'create' } %>

app/views/matches/score.html.erb
<header id="score">
  <div id="team1">
      <h1 class="popup">
        <%= @match.teams[0].name %>
      </h1>
    <%= image_tag("escudos/1.gif") %>
    <p><%= @match.value1.to_s %></p>
  </div>
  <div id="versus">
    <p>X</p>
  </div>
  <div id="team2">
    <p><%= @match.value2.to_s %></p>
    <%= image_tag("escudos/2.gif") %>
    <h1 class="popup">
      <%= @match.teams[1].name %>
    </h1>
  </div>
</header>

app/views/matches/show.html.erb
<%#A tabela das jogadas fica em moves/_move %>

<% content_for (:include_js) { 'matches' } %>

<% content_for :left_side_bar do %>
  <div class='thumbnail well'>
    <%= image_tag(@match.channel.avatar(:thumb_140), class: 'img img-polaroid') %>
    <h4 title='<%= @match.channel.name %>'>
      <%= @match.channel.name.truncate(15) %>
    </h4>
    <ul class="nav nav-list">
      <li>
        <%= link_to 'Página do Canal', channel_path(@match.channel) %>
      </li>
    </ul>
    <h4>Partidas</h4>
    <ul class="nav nav-list">
      <% @match.channel.matches.each do |m| %>
        <li class = <%= "active" if m.id == @match.id %> ><%= link_to m.name, match_path(m) %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<style>
    div.sc_menu {
      /* Set it so we could calculate the offsetLeft */
      position: relative;
      height: 145px;
      /*width: 500px;*/
      /* Add scroll-bars */
      overflow: auto;
    }

    ul.sc_menu {
      display: block;
      height: 110px;
      /* Max width here, for users without Javascript */
      width: 3000px;
      padding: 0px;
      /* Remove default margin */
      margin: 0;
      list-style: none;
    }

    .sc_menu li {
      display: block;
      float: left;
      padding: 0 4px;
    }

    .sc_menu a {
      display: block;
      text-decoration: none;
    }

    .sc_menu span {
      /* We want a caption to display on the next line */
      display: block;
      margin-top: 3px;
      text-align: center;
      font-size: 12px;
      color: black;
    }

    .sc_menu img {
      width: 80px;
      height: 80px;
    }
  </style>

<div id='pusher-warning' class='alert' style='display: none'>
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Atenção!</strong> Estamos buscando uma solução ilimitada para a quantidade
  de espectadores que recebem atualizações em tempo real. Por enquanto, essa
  capacidade é limitada e foi ultrapassada. Para visualizar novos lances,
  por favor, recarregue a página.
</div>

<% if can? :create, @move %>
  <div id="NewMoveForm" class="modal hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="modalTitle"></h3>
    </div>
    <div class='modal-body'>
      <%#TODO Transformar formulário abaixo em uma partial %>
      <%= form_for Move.new, url: { match_id: @match, action: 'create', controller: 'moves' },
        :html => { autocomplete: 'off' }, remote: 'true' do |f| %>
        <%= f.hidden_field :kind, id: 'kind', value: ''%>
        <div id='touchdown-kind' style="display: none;">
          <%= label :touchdown_kind, "Touchdown de:", diasplay: 'hidden' %>
          <%= select :touchdown, :kind,
            options_for_select([["Corrida", "touchdown-run"], ["Passe", "touchdown-pass"],
              ["Retorno", "touchdown-return"]]) %>
        </div>
        <div id='team' style="display: none;">
          <%= f.label :team %>
          <%= f.select :team,
            options_for_select(@match.teams.collect { |t| [t.name, t.id] }) %>
        </div>
        <div id='player' style="display: none;">
          <%= f.label :player %>
          <%= f.text_field :player, class: 'typeahead player',
            autocomplete: 'off' %>
          <span class="help-block">Ex.: #35 Terrence Cody</span>
        </div>
        <div id='yards' style="display: none;">
          <%= f.label :yards %>
          <%= f.number_field :yards %>
        </div>
        <div id='quarter' style="display: none;">
          <%= f.label :quarter %>
          <%= f.select :quarter, options_for_select([["--", 0], ["First", 1],
          ["Second", 2], ["Third", 3], ["Fourth", 4]]) %>
        </div>
        <div id='description' style="display: none;">
          <%= f.label :description %>
          <%= f.text_area :description, cols: "30", rows: "8", style: "resize: none;" %>
        </div>
        <div id='game-over' style="display: none;">
          Confirmar fim de jogo?
        </div>
        <div class="modal-fotter">
          <%= f.submit id: 'submit', class: 'btn', :'aria-hidden' => 'true' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="well hidden-tablet hidden-phone">
    <div class="sc_menu">
      <ul class="sc_menu">
        <% ['punt', 'extrapoint', 'penalty', 'kickoff', 'fumble',
          'run', 'turnover', 'time', 'touchdown', 'fieldgoal', 'pass', 'sack',
          'interception', 'end', 'safety', 'two-point-conversion', 'comment'].each do |kind| %>
          <li>
            <%= link_to '', class: 'linkModal', role: 'button',
              :'data-toggle' => 'modal', :'data-target' => "#NewMoveForm",
              value: kind, title: "#{t("moves.#{kind}")}" do %>
              <%= 's' unless kind == 'punt' %>
              <%= image_tag("icons/#{kind}.png", class: 'img-circle img-polaroid',
                style: 'width: 80px; height: 80px') %>
              <span><%= "#{t("moves.#{kind}")}" %></span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class=" well">
  <div class="visible-desktop">
    <div class="row-fluid">
      <div class="span4">
        <div class="hidden-phone"><%= @match.teams[0].name %></div>
        <div class="visible-phone"><%= @match.teams[0].abbreviation %> </div>
      </div>
      <div class="span4">
        <%= image_tag @match.teams[0].avatar(:thumb_90), style: "width: 60px; max-width:60px;" %>
        <span id='team1-score'><%= @match.value1.to_s %></span> X <span id='team2-score'><%= @match.value2.to_s %></span>
        <%= image_tag @match.teams[1].avatar(:thumb_90), style: "width: 60px; max-width:60px;" %>
      </div>
      <div class="span4">
        <div class="hidden-phone"><%= @match.teams[1].name %></div>
        <div class="visible-phone"><%= @match.teams[1].abbreviation %> </div>
      </div>
    </div>
  </div>

  <div class="hidden-desktop">
    <table class="table" style="margin-bottom: 0px">

      <thead>
        <tr>
          <td width="33%" style="text-align: right">
            <%= image_tag @match.teams[0].avatar(:thumb_90), style: "width: 50px" %><br />
            <%= @match.teams[0].abbreviation %>
          </td>
          <td width="33%"  style="text-align: center; white-space: nowrap">
            <h3> <%= @match.value1.to_s + " X " + @match.value2.to_s%> </h3>
          </td>
          <td width="33%" style="text-align: left">
            <%= image_tag @match.teams[1].avatar(:thumb_90),  style: "width: 50px" %><br />
            <%= @match.teams[1].abbreviation %>
          </td>
        </tr>
        </thead>

    </table>
  </div>
</div>
<% if can? :manege, @match %>

  <a class="btn hidden-desktop" data-target=".new-move-collapse" data-toggle="collapse">
    Nova Jogada
  </a>
  <div class="new-move-collapse collapse">
    <%= render partial: 'moves/mobile_form', locals: { action: 'create', remote: 'true',
            path: match_moves_path(@match) } %>
  </div>

<% end %>

  <div class="well">
    <table class="table table-striped">
      <thead>
        <tr>
          <th colspan="2">Lance a Lance</th>
        </tr>
      </thead>
      <tbody id='moves'>
        <% if @moves.empty? %> <%# Mensagens para quando a partida não possui jogadas %>
          <tr>
            <td>
              <div class='alert alert-info' id="empty-message">
                <% if @match.date <= Time.now # transmissão já deveria ter começado %>
                  A partida já deveria ter começado mas ainda nenhum lance foi adicionado. Talvez
                  <%= @match.channel.owner.first_name %>, o dono do canal, esteja atrasado.
                <% else %>
                  <strong>Oi, <%= current_user.try(:first_name) || 'torcedor(a)' %></strong>.
                  Que bom que você veio acompanhar esta partida! Ela está programada para começar
                  <%= l @match.date, format: :short %>h. Mas fique ligado! Novos lances podem
                  surgir mesmo antes do início da partida.
                <% end %>
              </div>
            </td>
          </tr>
        <% else %>
          <%= render partial: 'moves/move', collection: @moves,
            locals: { show_comment_button: 'true', show_edition_buttons: 'true' } %>
        <% end %>
      </tbody>
    </table>
    <%= link_to_unless(@moves.last_page?, "Mostrar mais...",
      match_moves_path(@match,
      page: (@moves.current_page+1)), rel: 'next', remote: true, class: 'btn',
      id: 'show-more', style: 'margin: auto;') do |name| %>
      <%= name = '' %> <%# # passa um bloco que apaga o 'Mostrar mais...' %>
    <% end %>
  </div>